var PRODUCT_IMAGES = {
  "iPhone 11_Červená": "batch1/iPhone_11_Cervena.jpg",
  "iPhone 11_Žlutá": "batch1/iPhone_11_Zluta.jpg",
  "iPhone 11_Fialová": "batch1/iPhone_11_Fialova.jpg",
  "iPhone 11_Bílá": "batch1/iPhone_11_Bila.jpg",
  "iPhone 11_Černá": "batch1/iPhone_11_Cerna.jpg",
  "iPhone 11_Zelená": "batch1/iPhone_11_Zelena.jpg",
  "iPhone 11 Pro_Temně zelená": "batch1/iPhone_11_Pro_Temne_zelena.jpg",
  "iPhone 11 Pro Max_Temně zelená": "batch1/iPhone_11_Pro_Max_Temne_zelena.jpg",
  "iPhone 11 Pro_Stříbrná": "batch1/iPhone_11_Pro_Stribrna.jpg",
  "iPhone 11 Pro Max_Stříbrná": "batch1/iPhone_11_Pro_Max_Stribrna.jpg",
  "iPhone 11 Pro_Zlatá": "batch1/iPhone_11_Pro_Zlata.jpg",
  "iPhone 11 Pro Max_Zlatá": "batch1/iPhone_11_Pro_Max_Zlata.jpg",
  "iPhone 11 Pro_Space Grey": "batch1/iPhone_11_Pro_Space_Grey.jpg",
  "iPhone 11 Pro Max_Space Grey": "batch1/iPhone_11_Pro_Max_Space_Grey.jpg",
  "iPhone 12 Pro_Graphite": "batch1/iPhone_12_Pro_Graphite.jpg",
  "iPhone 12 Pro Max_Graphite": "batch1/iPhone_12_Pro_Max_Graphite.jpg",
  "iPhone 12 Pro_Stříbrná": "batch1/iPhone_12_Pro_Stribrna.jpg",
  "iPhone 12 Pro Max_Stříbrná": "batch1/iPhone_12_Pro_Max_Stribrna.jpg",
  "iPhone 12 Pro_Zlatá": "batch1/iPhone_12_Pro_Zlata.jpg",
  "iPhone 12 Pro Max_Zlatá": "batch1/iPhone_12_Pro_Max_Zlata.jpg",
  "iPhone 12 Pro_Pacific Blue": "batch1/iPhone_12_Pro_Pacific_Blue.jpg",
  "iPhone 12 Pro Max_Pacific Blue": "batch1/iPhone_12_Pro_Max_Pacific_Blue.jpg",
  "iPhone 12_Bílá": "batch1/iPhone_12_Bila.jpg",
  "iPhone 12 Mini_Bílá": "batch1/iPhone_12_Mini_Bila.jpg",
  "iPhone 12_Fialová": "batch1/iPhone_12_Fialova.jpg",
  "iPhone 12 Mini_Fialová": "batch1/iPhone_12_Mini_Fialova.jpg",
  "iPhone 12_Zelená": "batch1/iPhone_12_Zelena.jpg",
  "iPhone 12 Mini_Zelená": "batch1/iPhone_12_Mini_Zelena.jpg",
  "iPhone 12_Černá": "batch1/iPhone_12_Cerna.jpg",
  "iPhone 12 Mini_Černá": "batch1/iPhone_12_Mini_Cerna.jpg",
  "iPhone 12_Červená": "batch1/iPhone_12_Cervena.jpg",
  "iPhone 12 Mini_Červená": "batch1/iPhone_12_Mini_Cervena.jpg",
  "iPhone 12_Modrá": "batch1/iPhone_12_Modra.jpg",
  "iPhone 12 Mini_Modrá": "batch1/iPhone_12_Mini_Modra.jpg",
  "iPhone 13_Starlight": "batch1/iPhone_13_Starlight.jpg",
  "iPhone 13 Mini_Starlight": "batch1/iPhone_13_Mini_Starlight.jpg",
  "iPhone 13_Červená": "batch1/iPhone_13_Cervena.jpg",
  "iPhone 13 Mini_Červená": "batch1/iPhone_13_Mini_Cervena.jpg",
  "iPhone 13_Růžová": "batch1/iPhone_13_Ruzova.jpg",
  "iPhone 13 Mini_Růžová": "batch1/iPhone_13_Mini_Ruzova.jpg",
  "iPhone 13_Zelená": "batch1/iPhone_13_Zelena.jpg",
  "iPhone 13 Mini_Zelená": "batch1/iPhone_13_Mini_Zelena.jpg",
  "iPhone 13_Midnight": "batch1/iPhone_13_Midnight.jpg",
  "iPhone 13 Mini_Midnight": "batch1/iPhone_13_Mini_Midnight.jpg",
  "iPhone 14_Starlight": "batch1/iPhone_14_Starlight.jpg",
  "iPhone 14 Plus_Starlight": "batch1/iPhone_14_Plus_Starlight.jpg",
  "iPhone 14_Červená": "batch1/iPhone_14_Cervena.jpg",
  "iPhone 14 Plus_Červená": "batch1/iPhone_14_Plus_Cervena.jpg",
  "iPhone 14_Modrá": "batch1/iPhone_14_Modra.jpg",
  "iPhone 14 Plus_Modrá": "batch1/iPhone_14_Plus_Modra.jpg",
  "iPhone 14_Fialová": "batch1/iPhone_14_Fialova.jpg",
  "iPhone 14 Plus_Fialová": "batch1/iPhone_14_Plus_Fialova.jpg",
  "iPhone 14_Midnight": "batch1/iPhone_14_Midnight.jpg",
  "iPhone 14 Plus_Midnight": "batch1/iPhone_14_Plus_Midnight.jpg",
  "iPhone 14_Žlutá": "batch1/iPhone_14_Zluta.jpg",
  "iPhone 14 Plus_Žlutá": "batch1/iPhone_14_Plus_Zluta.jpg",
  "iPhone 13 Pro_Stříbrná": "batch1/iPhone_13_Pro_Stribrna.jpg",
  "iPhone 13 Pro Max_Stříbrná": "batch1/iPhone_13_Pro_Max_Stribrna.jpg",
  "iPhone 13 Pro_Grafit": "batch1/iPhone_13_Pro_Grafit.jpg",
  "iPhone 13 Pro Max_Grafit": "batch1/iPhone_13_Pro_Max_Grafit.jpg",
  "iPhone 13 Pro_Alpine Green": "batch1/iPhone_13_Pro_Alpine_Green.jpg",
  "iPhone 13 Pro Max_Alpine Green": "batch1/iPhone_13_Pro_Max_Alpine_Green.jpg",
  "iPhone 13_Modrá": "batch1/iPhone_13_Modra.jpg",
  "iPhone 13 Mini_Modrá": "batch1/iPhone_13_Mini_Modra.jpg",
  "iPhone 13 Pro_Sierra Blue": "batch1/iPhone_13_Pro_Sierra_Blue.jpg",
  "iPhone 13 Pro Max_Sierra Blue": "batch1/iPhone_13_Pro_Max_Sierra_Blue.jpg",
  "iPhone 13 Pro_Zlatá": "batch1/iPhone_13_Pro_Zlata.jpg",
  "iPhone 13 Pro Max_Zlatá": "batch1/iPhone_13_Pro_Max_Zlata.jpg",
  "iPhone 14 Pro_Zlatá": "batch1/iPhone_14_Pro_Zlata.jpg",
  "iPhone 14 Pro Max_Zlatá": "batch1/iPhone_14_Pro_Max_Zlata.jpg",
  "iPhone 14 Pro_Temná fialová": "batch1/iPhone_14_Pro_Temna_fialova.jpg",
  "iPhone 14 Pro Max_Temná fialová": "batch1/iPhone_14_Pro_Max_Temna_fialova.jpg",
  "iPhone 14 Pro_Stříbrná": "batch1/iPhone_14_Pro_Stribrna.jpg",
  "iPhone 14 Pro Max_Stříbrná": "batch1/iPhone_14_Pro_Max_Stribrna.jpg",
  "iPhone 14 Pro_Space Black": "batch1/iPhone_14_Pro_Space_Black.jpg",
  "iPhone 14 Pro Max_Space Black": "batch1/iPhone_14_Pro_Max_Space_Black.jpg",
  "iPhone 15_Zelená": "batch2/iPhone_15_Zelena.jpg",
  "iPhone 15 Plus_Zelená": "batch2/iPhone_15_Plus_Zelena.jpg",
  "iPhone 15_Růžová": "batch2/iPhone_15_Ruzova.jpg",
  "iPhone 15 Plus_Růžová": "batch1/iPhone_15_Plus_Ruzova.jpg",
  "iPhone 15_Žlutá": "batch2/iPhone_15_Zluta.jpg",
  "iPhone 15 Plus_Žlutá": "batch2/iPhone_15_Plus_Zluta.jpg",
  "iPhone 15_Černá": "batch2/iPhone_15_Cerna.jpg",
  "iPhone 15 Plus_Černá": "batch2/iPhone_15_Plus_Cerna.jpg",
  "iPhone 15_Modrá": "batch1/iPhone_15_Modra.jpg",
  "iPhone 15 Plus_Modrá": "batch1/iPhone_15_Plus_Modra.jpg",
  "iPhone 15 Pro_Černý titan": "batch2/iPhone_15_Pro_Cerny_titan.jpg",
  "iPhone 15 Pro Max_Černý titan": "batch2/iPhone_15_Pro_Max_Cerny_titan.jpg",
  "iPhone 15 Pro_Bílý titan": "batch2/iPhone_15_Pro_Bily_titan.jpg",
  "iPhone 15 Pro Max_Bílý titan": "batch2/iPhone_15_Pro_Max_Bily_titan.jpg",
  "iPhone 15 Pro_Přírodní titan": "batch2/iPhone_15_Pro_Prirodni_titan.jpg",
  "iPhone 15 Pro Max_Přírodní titan": "batch2/iPhone_15_Pro_Max_Prirodni_titan.jpg",
  "iPhone 15 Pro_Modrý titan": "batch2/iPhone_15_Pro_Modry_titan.jpg",
  "iPhone 15 Pro Max_Modrý titan": "batch2/iPhone_15_Pro_Max_Modry_titan.jpg",
  "iPhone 16_Black": "batch2/iPhone_16_Black.jpg",
  "iPhone 16 Plus_Black": "batch2/iPhone_16_Plus_Black.jpg",
  "iPhone 16_White": "batch2/iPhone_16_White.jpg",
  "iPhone 16 Plus_White": "batch2/iPhone_16_Plus_White.jpg",
  "iPhone 16_Pink": "batch2/iPhone_16_Pink.jpg",
  "iPhone 16 Plus_Pink": "batch2/iPhone_16_Plus_Pink.jpg",
  "iPhone 16_Teal": "batch2/iPhone_16_Teal.jpg",
  "iPhone 16 Plus_Teal": "batch2/iPhone_16_Plus_Teal.jpg",
  "iPhone 16_Ultramarine": "batch2/iPhone_16_Ultramarine.jpg",
  "iPhone 16 Plus_Ultramarine": "batch2/iPhone_16_Plus_Ultramarine.jpg",
  "iPhone 16 Pro_Přírodní titan": "batch2/iPhone_16_Pro_Prirodni_titan.jpg",
  "iPhone 16 Pro Max_Přírodní titan": "batch2/iPhone_16_Pro_Max_Prirodni_titan.jpg",
  "iPhone 16 Pro_Pouštní titan": "batch2/iPhone_16_Pro_Poustni_titan.jpg",
  "iPhone 16 Pro Max_Pouštní titan": "batch2/iPhone_16_Pro_Max_Poustni_titan.jpg",
  "iPhone 16 Pro_Černý titan": "batch2/iPhone_16_Pro_Cerny_titan.jpg",
  "iPhone 16 Pro Max_Černý titan": "batch2/iPhone_16_Pro_Max_Cerny_titan.jpg",
  "iPhone 16 Pro_Bílý titan": "batch2/iPhone_16_Pro_Bily_titan.jpg",
  "iPhone 16 Pro Max_Bílý titan": "batch2/iPhone_16_Pro_Max_Bily_titan.jpg",
  "iPhone 16e_Černá": "batch2/iPhone_16e_Cerna.jpg",
  "iPhone 16e_Bílá": "batch2/iPhone_16e_Bila.jpg",
  "iPhone 17 Air (2025)_Light Gold": "batch2/iPhone_17_Air_Light_Gold.jpg",
  "iPhone 17 Air (2025)_Sky Blue": "batch2/iPhone_17_Air_Sky_Blue.jpg",
  "iPhone 17 Air (2025)_Space Black": "batch2/iPhone_17_Air_Space_Black.jpg",
  "iPhone 17 Air (2025)_Cloud White": "batch2/iPhone_17_Air_Cloud_White.jpg",
  "iPhone 17_White": "batch2/iPhone_17_White.jpg",
  "iPhone 17_Black": "batch2/iPhone_17_Black.jpg",
  "iPhone 17_Lavender": "batch2/iPhone_17_Lavender.jpg",
  "iPhone 17_Sage": "batch2/iPhone_17_Sage.jpg",
  "iPhone 17_Mist Blue": "batch2/iPhone_17_Mist_Blue.jpg",
  "iPhone 17 Plus_White": "batch2/iPhone_17_Plus_White.jpg",
  "iPhone 17 Plus_Black": "batch2/iPhone_17_Plus_Black.jpg",
  "iPhone 17 Plus_Lavender": "batch2/iPhone_17_Plus_Lavender.jpg",
  "iPhone 17 Plus_Sage": "batch2/iPhone_17_Plus_Sage.jpg",
  "iPhone 17 Plus_Mist Blue": "batch2/iPhone_17_Plus_Mist_Blue.jpg",
  "iPhone 17 Pro_Deep Blue": "batch2/iPhone_17_Pro_Deep_Blue.jpg",
  "iPhone 17 Pro Max_Deep Blue": "batch2/iPhone_17_Pro_Max_Deep_Blue.jpg",
  "iPhone 17 Pro_Silver": "batch2/iPhone_17_Pro_Silver.jpg",
  "iPhone 17 Pro Max_Silver": "batch2/iPhone_17_Pro_Max_Silver.jpg",
  "iPhone 17 Pro_Cosmic Orange": "batch2/iPhone_17_Pro_Cosmic_Orange.jpg",
  "iPhone 17 Pro Max_Cosmic Orange": "batch2/iPhone_17_Pro_Max_Cosmic_Orange.jpg",
  "iPhone SE (2020)_Černá": "batch2/iPhone_SE_2020_Cerna.jpg",
  "iPhone SE (2020)_Bílá": "batch2/iPhone_SE_2020_Bila.jpg",
  "iPhone SE (2020)_Červená": "batch2/iPhone_SE_2020_Cervena.jpg",
  "iPhone SE (2022)_Midnight": "batch2/iPhone_SE_2022_Midnight.jpg",
  "iPhone SE (2022)_Starlight": "batch2/iPhone_SE_2022_Starlight.jpg",
  "iPhone SE (2022)_Červená": "batch2/iPhone_SE_2022_Cervena.jpg",
  "iPhone XR_Červená": "batch2/iPhone_XR_Cervena.jpg",
  "iPhone XR_Korálová": "batch2/iPhone_XR_Koralova.jpg",
  "iPhone XR_Žlutá": "batch2/iPhone_XR_Zluta.jpg",
  "iPhone XR_Bílá": "batch2/iPhone_XR_Bila.jpg",
  "iPhone XR_Černá": "batch2/iPhone_XR_Cerna.jpg",
  "iPhone XR_Modrá": "batch2/iPhone_XR_Modra.jpg",
  "iPhone X_Space Grey": "batch2/iPhone_X_Space_Grey.jpg",
  "iPhone X_Silver": "batch2/iPhone_X_Silver.jpg",
  "iPhone XS_Gold": "batch2/iPhone_XS_Gold.jpg",
  "iPhone XS_Silver": "batch2/iPhone_XS_Silver.jpg",
  "iPhone XS_Space Grey": "batch2/iPhone_XS_Space_Grey.jpg",
  "iPhone XS Max_Gold": "batch2/iPhone_XS_Max_Gold.jpg",
  "iPhone XS Max_Silver": "batch2/iPhone_XS_Max_Silver.jpg",
  "iPhone XS Max_Space Grey": "batch2/iPhone_XS_Max_Space_Grey.jpg"
};
